
version: '3'

services:

    swarm:
        build: ../
        volumes:
            - ../:/var/www/node
        ports:
            - 8181:8181
        networks:
            - swarm-net

networks:
    swarm-net:
        driver: bridge
